name: PipelineFlaskPOC

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Executar Testes
      run: |
        if [ -f app_test.py ]; then
          pytest app_test.py
        fi

    - name: Relatório de Cobertura
      run: |
        if [ -f app_test.py ]; then
          coverage run -m pytest app_test.py
          coverage report -m
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Deploy no Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

    - name: Deploy no EC2 AWS
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        echo "${{ secrets.AWS_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@<EC2_PUBLIC_IP> "
          cd /var/www/html/POC &&
          git pull &&
          source venv/bin/activate &&
          ./executar.sh"
